apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-config
data:
  DATABASE_URL: "postgres://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@postgresql:5432/{{ .Values.postgresql.database }}"
